
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - nirmata-workflow.nirmata.io
  resources:
  - workflowtasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nirmata-workflow.nirmata.io
  resources:
  - workflowtasks/finalizers
  verbs:
  - update
- apiGroups:
  - nirmata-workflow.nirmata.io
  resources:
  - workflowtasks/status
  verbs:
  - get
  - patch
  - update
